name: CI

on:
  push:
    branches: [feature/**]
  pull_request:
    branches: [main]
    types: [ opened ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d # v22
        with:
          servers: >
            [
              {
                "id": "github-prv",
                "username": "${{secrets.GH_PRV_USERNAME}}",
                "password": "${{secrets.GH_PRV_PASSWORD}}"
              },
              {
                "id": "github-org-smart-home",
                "username": "${{secrets.GH_PRV_USERNAME}}",
                "password": "${{secrets.GH_PRV_PASSWORD}}"
              }
            ]

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          overwrite-settings: false

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Discord notification -> success
        uses: sarisia/actions-status-discord@b8381b25576cb341b2af39926ab42c5056cc44ed #v1.15.5
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "CI water-service - success"
      - name: Discord notification -> non-success
        uses: sarisia/actions-status-discord@b8381b25576cb341b2af39926ab42c5056cc44ed #v1.15.5
        if: ${{ !success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "CI water-service - failure"
