name: release

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get tag
        id: version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "GIT_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo 'latest')" >> $GITHUB_OUTPUT
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github-prv
          server-username: x-access-token
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Maven settings for organization
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github-org-smart-home
          server-username: x-access-token
          server-password: ${{ secrets.GITHUB_TOKEN }}
          overwrite-settings: false

      - name: Set project version
        run: mvn versions:set -DnewVersion=${{ steps.version.outputs.GIT_TAG }}

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Log in to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 #v5
        with:
          images: magikabdul/water-service
          tags: |
            type=raw,value=latest
            type=raw,value=${{ steps.version.outputs.GIT_TAG }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 #v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
